version: '2'

services:

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    links:
      - node1:node1
      - node2:node2
      - node3:node3
      - node4:node4
      - node5:node5
      - node6:node6
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
    ports:
      - "8080:80"
    networks:
      - beingzero-lb

  node1:
    build: src
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
    networks:
      - beingzero-lb

  node2:
    build: src
    ports:
      - "3000"
    environment:
      - INSTANCE=node2
    networks:
      - beingzero-lb

  node3:
    build: src
    ports:
      - "3000"
    environment:
      - INSTANCE=node3
    networks:
      - beingzero-lb

  node4:
    build: src
    ports:
      - "3000"
    environment:
      - INSTANCE=node4
    networks:
      - beingzero-lb

  node5:
    build: src
    ports:
      - "3000"
    environment:
      - INSTANCE=node5
    networks:
      - beingzero-lb

  node6:
    build: src
    ports:
      - "3000"
    environment:
      - INSTANCE=node6
    networks:
      - beingzero-lb

networks:
  beingzero-lb:
    driver: bridge
