version: '2'

services:

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
    volumes: 
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - beingzero-lb

  node1:
    build: src
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
    networks:
      - beingzero-lb

  node2:
    build: src
    ports:
      - "3000"
    environment:
      - INSTANCE=node2
    networks:
      - beingzero-lb

  node3:
    build: src
    ports:
      - "3000"
    environment:
      - INSTANCE=node3
    networks:
      - beingzero-lb

networks:
  beingzero-lb:
    driver: bridge
